version: '3.7'

services:
  web:
    build: .
    command: php artisan serve --host=0.0.0.0 --port=8080
    ports:
      - "8081:8080"
    volumes:
      - .:/var/www
  mariadb:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql